import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './openapi-spec'; // generated by openapi-typescript

export const API_BASE_URL = '/';

export function getClient<Paths extends object = paths>({ baseUrl }: { baseUrl: string }) {
    return createFetchClient<Paths>({ baseUrl });
}

export const fetchClient = getClient({ baseUrl: API_BASE_URL });

export const $api = createClient(fetchClient);
